'use client'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { Activity, Bell, LayoutDashboard, Menu, Search, Settings2, Star, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { MARKET_DATA } from '@/lib/market-data'

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false); const [query, setQuery] = useState('')
  const results = useMemo(() => query ? MARKET_DATA.filter(s => `${s.symbol} ${s.name}`.toLowerCase().includes(query.toLowerCase())) : [], [query])
  const nav = [{ href: '/', label: 'Overview', icon: LayoutDashboard }, { href: '/watchlists', label: 'Watchlists', icon: Star }, { href: '/insights', label: 'Insights', icon: Bell }, { href: '/settings', label: 'Settings', icon: Settings2 }]
  return <div className="min-h-screen bg-background text-foreground"><aside className="fixed inset-y-0 left-0 z-20 hidden w-64 flex-col border-r border-border bg-card p-6 lg:flex"><Brand /><nav className="mt-12 flex flex-col gap-2">{nav.map(item => <Link key={item.href} href={item.href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm ${pathname === item.href ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'}`}><item.icon className="size-4" />{item.label}</Link>)}</nav><div className="mt-auto text-xs text-muted-foreground">Smart market intelligence<br />NSE · Demo feed</div></aside><main className="lg:pl-64"><header className="flex min-h-20 items-center gap-4 border-b border-border px-5 py-4 sm:px-8"><button className="lg:hidden" aria-label="Open menu" onClick={() => setOpen(!open)}>{open ? <X className="size-5" /> : <Menu className="size-5" />}</button><div className="relative ml-auto w-full max-w-xs"><Search className="pointer-events-none absolute left-3 top-2.5 size-4 text-muted-foreground" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search stocks" className="h-9 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-ring" />{results.length > 0 && <div className="absolute top-11 z-30 w-full rounded-xl border border-border bg-card p-2 shadow-lg">{results.map(stock => <button key={stock.symbol} onClick={() => { router.push(`/stock/${stock.symbol}`); setQuery('') }} className="flex w-full flex-col gap-0.5 rounded-lg px-3 py-2 text-left hover:bg-muted"><span className="text-sm font-semibold">{stock.symbol}</span><span className="text-xs text-muted-foreground">{stock.name}</span></button>)}</div>}</div><span className="hidden text-sm text-muted-foreground sm:block">Friday, September 4, 2026</span></header>{open && <nav className="flex flex-col gap-2 border-b border-border bg-card p-4 lg:hidden">{nav.map(item => <Link onClick={() => setOpen(false)} key={item.href} href={item.href} className="rounded-lg px-3 py-2 text-sm">{item.label}</Link>)}</nav>}{children}</main></div>
}
function Brand() { return <div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Activity className="size-5" /></div><div><p className="font-semibold tracking-tight">SmartWatch</p><p className="text-xs text-muted-foreground">Market intelligence</p></div></div> }
export function PageFrame({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <section className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-balance sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p><div className="mt-8">{children}</div></section> }
export function ShellPage({ children }: { children: React.ReactNode }) { return <AppShell>{children}</AppShell> }
export function scoreColor(signal: string) { return signal === 'Critical' ? 'text-primary' : signal === 'Important' ? 'text-amber-700' : signal === 'Stable' ? 'text-muted-foreground' : 'text-foreground' }
