'use client'

import { useMemo, useState } from 'react'
import { Activity, Bell, ChevronDown, ChevronUp, CircleHelp, Clock3, LayoutDashboard, LogOut, Menu, Plus, RefreshCw, Search, Settings2, SlidersHorizontal, Star, TrendingDown, TrendingUp, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { createClient } from '@/lib/supabase/client'

type Stock = { symbol: string; name: string; sector: string; price: number; change: number; volume: string; signal: 'High' | 'Medium' | 'Low'; note: string }
const seed: Stock[] = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Energy', price: 2938.4, change: 4.82, volume: '2.4M', signal: 'High', note: 'Price moved 4.8% with 2.1x average volume' },
  { symbol: 'TCS', name: 'Tata Consultancy Services', sector: 'Technology', price: 3812.15, change: -2.14, volume: '1.1M', signal: 'Medium', note: 'Price moved beyond your 2% threshold' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Financials', price: 1742.8, change: 1.36, volume: '3.8M', signal: 'Low', note: 'Stable movement within your watch range' },
  { symbol: 'INFY', name: 'Infosys', sector: 'Technology', price: 1498.6, change: 3.72, volume: '1.9M', signal: 'High', note: 'Price moved 3.7% with unusually high activity' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Financials', price: 1224.25, change: 0.84, volume: '2.1M', signal: 'Low', note: 'No meaningful change since your last visit' },
]

export function SmartWatchDashboard() {
  const [stocks, setStocks] = useState(seed)
  const [active, setActive] = useState('Overview')
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState<'All' | 'High' | 'Medium' | 'Low'>('All')
  const [sortAsc, setSortAsc] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [refreshed, setRefreshed] = useState(false)
  const [threshold, setThreshold] = useState(2)

  const visible = useMemo(() => stocks.filter((s) => (filter === 'All' || s.signal === filter) && `${s.symbol} ${s.name}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sortAsc ? a.change - b.change : b.change - a.change), [stocks, filter, query, sortAsc])
  const high = stocks.filter((s) => s.signal === 'High').length

  async function signOut() { await createClient().auth.signOut(); window.location.reload() }
  function refresh() { setRefreshed(true); setStocks((items) => items.map((s) => ({ ...s, price: +(s.price * (1 + (Math.random() - .5) / 100)).toFixed(2) }))); setTimeout(() => setRefreshed(false), 1400) }

  return <div className="min-h-screen bg-background text-foreground">
    <aside className="fixed inset-y-0 left-0 z-20 hidden w-64 flex-col border-r border-border bg-card p-6 lg:flex">
      <div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Activity className="size-5" /></div><div><p className="font-semibold tracking-tight">SmartWatch</p><p className="text-xs text-muted-foreground">Market intelligence</p></div></div>
      <nav className="mt-12 flex flex-col gap-2">{['Overview','Watchlists','Alerts','Settings'].map((item) => <button key={item} onClick={() => setActive(item)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${active === item ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><NavIcon item={item} />{item}</button>)}</nav>
      <div className="mt-auto flex flex-col gap-3"><button className="flex items-center gap-3 px-3 py-2 text-sm text-muted-foreground hover:text-foreground"><CircleHelp className="size-4" />Help center</button><button onClick={signOut} className="flex items-center gap-3 px-3 py-2 text-sm text-muted-foreground hover:text-foreground"><LogOut className="size-4" />Sign out</button></div>
    </aside>
    <main className="lg:pl-64"><header className="flex h-20 items-center justify-between border-b border-border px-5 sm:px-8"><button onClick={() => setMenuOpen(!menuOpen)} className="lg:hidden"><Menu className="size-5" /></button><div className="hidden lg:block"><p className="text-sm text-muted-foreground">Friday, September 4, 2026</p><h1 className="text-lg font-semibold">Good morning, investor</h1></div><div className="ml-auto flex items-center gap-3"><Button variant="outline" size="sm" onClick={refresh} disabled={refreshed}><RefreshCw className={`mr-2 size-4 ${refreshed ? 'animate-spin' : ''}`} />Refresh data</Button><button aria-label="Notifications" className="relative rounded-lg p-2 hover:bg-muted"><Bell className="size-5 text-muted-foreground" /><span className="absolute right-1 top-1 size-2 rounded-full bg-primary" /></button><div className="flex size-9 items-center justify-center rounded-full bg-secondary text-sm font-semibold">AS</div></div></header>
      {menuOpen && <div className="border-b border-border bg-card p-4 lg:hidden"><div className="flex flex-col gap-2">{['Overview','Watchlists','Alerts','Settings'].map((item) => <button key={item} onClick={() => { setActive(item); setMenuOpen(false) }} className="rounded-lg px-3 py-2 text-left text-sm hover:bg-muted">{item}</button>)}</div></div>}
      <div className="mx-auto max-w-7xl p-5 sm:p-8"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-medium text-primary">Your market pulse</p><h2 className="text-3xl font-semibold tracking-tight text-balance">Focus on what changed<br className="hidden sm:block" /> since your last visit.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">A calm, explainable view of the stocks that deserve your attention.</p></div><div className="flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2 text-xs text-muted-foreground"><Clock3 className="size-3.5" />Last checked 9:42 AM IST</div></div>
        <section className="grid gap-4 md:grid-cols-3"><SummaryCard label="Needs attention" value={high.toString().padStart(2, '0')} copy="meaningful changes detected" tone="primary" /><SummaryCard label="Market status" value="Open" copy="NSE · closes in 5h 18m" tone="green" /><SummaryCard label="Your threshold" value={`${threshold}%`} copy="price change sensitivity" tone="neutral" /></section>
        <section className="mt-8 grid gap-5 xl:grid-cols-[1fr_300px]"><div className="rounded-2xl border border-border bg-card"><div className="flex flex-col gap-4 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h3 className="font-semibold">My watchlist</h3><span className="rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">{stocks.length} stocks</span></div><p className="mt-1 text-sm text-muted-foreground">Sorted by meaningful change</p></div><Button variant="outline" size="sm"><Plus className="mr-2 size-4" />Add stock</Button></div><div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search stocks" className="h-9 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></div><div className="flex items-center gap-1 rounded-lg bg-muted p-1">{(['All','High','Medium','Low'] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-md px-2.5 py-1.5 text-xs ${filter === item ? 'bg-card font-medium shadow-sm' : 'text-muted-foreground'}`}>{item}</button>)}</div><button onClick={() => setSortAsc(!sortAsc)} className="rounded-lg border border-input p-2 text-muted-foreground hover:bg-muted" aria-label="Sort"><SlidersHorizontal className="size-4" /></button></div><div className="divide-y divide-border">{visible.map((stock) => <StockRow key={stock.symbol} stock={stock} onRemove={() => setStocks(stocks.filter((s) => s.symbol !== stock.symbol))} />)}{visible.length === 0 && <div className="p-10 text-center text-sm text-muted-foreground">No stocks match your search.</div>}</div></div>
          <aside className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Change engine</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">How SmartWatch decides what matters.</p></div><Settings2 className="size-5 text-primary" /></div><div className="mt-6 flex flex-col gap-5"><EngineRow label="Price movement" value="40%" /><EngineRow label="Volume anomaly" value="25%" /><EngineRow label="Volatility" value="20%" /><EngineRow label="Freshness" value="15%" /></div><div className="mt-6 border-t border-border pt-5"><label className="flex items-center justify-between text-xs font-medium"><span>Alert threshold</span><span className="text-primary">{threshold}%</span></label><input type="range" min="1" max="8" step=".5" value={threshold} onChange={(e) => setThreshold(+e.target.value)} className="mt-3 w-full accent-primary" /><div className="mt-1 flex justify-between text-[10px] text-muted-foreground"><span>More sensitive</span><span>Less noise</span></div></div></aside></section>
        <p className="mt-5 flex items-center justify-center gap-2 text-xs text-muted-foreground"><span className="size-1.5 rounded-full bg-primary" />Data is delayed up to 15 minutes · Built for better decisions, not constant checking.</p>
      </div></main>
  </div>
}
function NavIcon({ item }: { item: string }) { const Icon = item === 'Overview' ? LayoutDashboard : item === 'Watchlists' ? Star : item === 'Alerts' ? Bell : Settings2; return <Icon className="size-4" /> }
function SummaryCard({ label, value, copy, tone }: { label: string; value: string; copy: string; tone: string }) { return <div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><div className="mt-3 flex items-end gap-3"><p className={`text-3xl font-semibold ${tone === 'primary' ? 'text-primary' : tone === 'green' ? 'text-emerald-600' : ''}`}>{value}</p><p className="mb-1 text-xs text-muted-foreground">{copy}</p></div></div> }
function EngineRow({ label, value }: { label: string; value: string }) { return <div><div className="flex justify-between text-xs"><span>{label}</span><span className="font-medium text-muted-foreground">{value}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: value }} /></div></div> }
function StockRow({ stock, onRemove }: { stock: Stock; onRemove: () => void }) { const up = stock.change > 0; return <div className="flex items-center gap-3 p-4 sm:gap-5"><div className={`flex size-10 shrink-0 items-center justify-center rounded-xl ${up ? 'bg-emerald-500/10 text-emerald-600' : 'bg-rose-500/10 text-rose-600'}`}>{up ? <TrendingUp className="size-5" /> : <TrendingDown className="size-5" />}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-medium">{stock.symbol}</p><span className="hidden text-xs text-muted-foreground sm:inline">{stock.name}</span></div><p className="mt-1 truncate text-xs text-muted-foreground">{stock.note}</p></div><div className="hidden text-right sm:block"><p className="font-medium">₹{stock.price.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</p><p className={`mt-1 text-xs font-medium ${up ? 'text-emerald-600' : 'text-rose-600'}`}>{up ? '+' : ''}{stock.change.toFixed(2)}%</p></div><div className="hidden w-16 text-right md:block"><p className="text-xs text-muted-foreground">Volume</p><p className="mt-1 text-sm">{stock.volume}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${stock.signal === 'High' ? 'bg-primary/10 text-primary' : stock.signal === 'Medium' ? 'bg-amber-500/10 text-amber-700' : 'bg-muted text-muted-foreground'}`}>{stock.signal}</span><button onClick={onRemove} aria-label={`Remove ${stock.symbol}`} className="rounded-md p-1 text-muted-foreground hover:bg-muted hover:text-foreground"><X className="size-4" /></button></div> }
